-- Cria a tabela de armazenamento de usuários
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  login TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de armazenamento de módulos
CREATE TABLE IF NOT EXISTS module (
  module_id INTEGER PRIMARY KEY AUTOINCREMENT,
  module_name TEXT UNIQUE NOT NULL,
  description TEXT,
  count_total_access INTEGER NOT NULL DEFAULT 0,
  record_user_id INTEGER,
  record_value INTEGER DEFAULT 0,
  record_datetime TIMESTAMP,
  FOREIGN KEY (record_user_id) REFERENCES user (id)
);

-- Tabela de armazenamento dos scores do usuário.
CREATE TABLE IF NOT EXISTS score (
  user_id INTEGER NOT NULL,
  module_id INTEGER NOT NULL,
  total_score INTEGER NOT NULL DEFAULT 0,
  count_access INTEGER NOT NULL DEFAULT 1,
  record INTEGER DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES user (id),
  FOREIGN KEY (module_id) REFERENCES module (module_id)
);

-- Tabela de definição das categorias de palavras.
CREATE TABLE IF NOT EXISTS categories (category VARCHAR(50) PRIMARY KEY);

-- Tabela de definição da estrutura das palavras.
CREATE TABLE IF NOT EXISTS words (
  id INTEGER PRIMARY KEY,
  category VARCHAR(50),
  br_word VARCHAR(80),
  en_word VARCHAR(80),
  FOREIGN KEY (category) REFERENCES categories (name)
);

-- Inserir as categorias na tabela 'categories'
INSERT
OR IGNORE INTO categories (category)
VALUES
  ('weekdays'),
  ('weekends'),
  ('colors'),
  ('verbs'),
  ('geometric forms');

-- Inserir as palavras nas tabelas 'words'
INSERT
OR IGNORE INTO words (id, category, br_word, en_word)
VALUES
  (1, 'weekdays', 'segunda-feira', 'Monday'),
  (2, 'weekdays', 'terça-feira', 'Tuesday'),
  (3, 'weekdays', 'quarta-feira', 'Wednesday'),
  (4, 'weekdays', 'quinta-feira', 'Thursday'),
  (5, 'weekdays', 'sexta-feira', 'Friday'),
  (6, 'weekends', 'sábado', 'Saturday'),
  (7, 'weekends', 'domingo', 'Sunday'),
  (8, 'colors', 'vermelho', 'red'),
  (9, 'colors', 'azul', 'blue'),
  (10, 'colors', 'verde', 'green'),
  (11, 'colors', 'amarelo', 'yellow'),
  (12, 'colors', 'preto', 'black'),
  (13, 'colors', 'branco', 'white'),
  (14, 'colors', 'laranja', 'orange'),
  (15, 'colors', 'roxo', 'purple'),
  (16, 'colors', 'rosa', 'pink'),
  (17, 'colors', 'marrom', 'brown'),
  (18, 'colors', 'cinza', 'gray'),
  (19, 'geometric forms', 'quadrado', 'square'),
  (20, 'geometric forms', 'círculo', 'circle'),
  (21, 'geometric forms', 'triângulo', 'triangle'),
  (22, 'geometric forms', 'retângulo', 'rectangle'),
  (23, 'verbs', 'ser, estar', 'to be'),
  (24, 'verbs', 'ter', 'to have'),
  (25, 'verbs', 'fazer', 'to do'),
  (26, 'verbs', 'dizer', 'to say'),
  (27, 'verbs', 'obter, conseguir', 'to get'),
  (28, 'verbs', 'fazer, criar', 'to make'),
  (29, 'verbs', 'ir', 'to go'),
  (30, 'verbs', 'saber, conhecer', 'to know'),
  (31, 'verbs', 'pegar, levar', 'to take'),
  (32, 'verbs', 'ver', 'to see'),
  (33, 'verbs', 'vir', 'to come'),
  (34, 'verbs', 'pensar', 'to think'),
  (35, 'verbs', 'olhar', 'to look'),
  (36, 'verbs', 'querer', 'to want'),
  (37, 'verbs', 'dar', 'to give'),
  (38, 'verbs', 'usar', 'to use'),
  (39, 'verbs', 'encontrar', 'to find'),
  (40, 'verbs', 'contar', 'to tell'),
  (41, 'verbs', 'perguntar', 'to ask'),
  (42, 'verbs', 'trabalhar', 'to work'),
  (43, 'verbs', 'parecer', 'to appear'),
  (44, 'verbs', 'sentir', 'to feel'),
  (45, 'verbs', 'tentar', 'to try'),
  (46, 'verbs', 'chamar', 'to call'),
  (47, 'verbs', 'precisar', 'to need'),
  (48, 'verbs', 'tornar-se', 'to become'),
  (49, 'verbs', 'sair, deixar', 'to leave'),
  (50, 'verbs', 'colocar, pôr', 'to put'),
  (51, 'verbs', 'significar', 'to mean'),
  (52, 'verbs', 'manter', 'to keep'),
  (53, 'verbs', 'deixar, permitir', 'to let'),
  (54, 'verbs', 'começar', 'to begin'),
  (55, 'verbs', 'ajudar', 'to help'),
  (56, 'verbs', 'conversar', 'to talk'),
  (57, 'verbs', 'mudar', 'to change'),
  (58, 'verbs', 'mostrar', 'to show'),
  (59, 'verbs', 'ouvir', 'to hear'),
  (60, 'verbs', 'jogar, tocar', 'to play'),
  (61, 'verbs', 'correr', 'to run'),
  (62, 'verbs', 'mover', 'to move'),
  (63, 'verbs', 'viver', 'to live'),
  (64, 'verbs', 'acreditar', 'to believe'),
  (65, 'verbs', 'segurar', 'to hold'),
  (66, 'verbs', 'trazer', 'to bring'),
  (67, 'verbs', 'acontecer', 'to happen'),
  (68, 'verbs', 'escrever', 'to write'),
  (69, 'verbs', 'sentar', 'to sit'),
  (70, 'verbs', 'parar', 'to stop'),
  (71, 'verbs', 'ler', 'to read'),
  (72, 'verbs', 'entender', 'to understand'),
  (73, 'verbs', 'encontrar, conhecer', 'to meet'),
  (74, 'verbs', 'ganhar', 'to win'),
  (75, 'verbs', 'falar', 'to speak'),
  (76, 'verbs', 'começar', 'to start'),
  (77, 'verbs', 'estar, ficar', 'to stand'),
  (78, 'verbs', 'perder', 'to lose'),
  (79, 'verbs', 'pagar', 'to pay'),
  (80, 'verbs', 'incluir', 'to include'),
  (81, 'verbs', 'continuar', 'to continue'),
  (82, 'verbs', 'aprender', 'to learn'),
  (83, 'verbs', 'comprar', 'to buy'),
  (84, 'verbs', 'enviar', 'to send'),
  (85, 'verbs', 'construir', 'to build'),
  (86, 'verbs', 'morrer', 'to die'),
  (87, 'verbs', 'ter, segurar', 'to hold'),
  (88, 'verbs', 'receber', 'to receive'),
  (89, 'verbs', 'criar', 'to create'),
  (90, 'verbs', 'subir, crescer', 'to grow'),
  (91, 'verbs', 'quebrar', 'to break'),
  (92, 'verbs', 'enviar', 'to send'),
  (93, 'verbs', 'chegar', 'to arrive'),
  (94, 'verbs', 'esperar', 'to wait'),
  (95, 'verbs', 'cair', 'to fall'),
  (96, 'verbs', 'puxar', 'to pull'),
  (97, 'verbs', 'empurrar', 'to push'),
  (98, 'verbs', 'comprar', 'to buy'),
  (99, 'verbs', 'vender', 'to sell'),
  (100, 'verbs', 'gastar', 'to spend'),
  (101, 'verbs', 'enviar, mandar', 'to send'),
  (102, 'verbs', 'acordar', 'to wake'),
  (103, 'verbs', 'dormir', 'to sleep'),
  (104, 'verbs', 'comer', 'to eat'),
  (105, 'verbs', 'beber', 'to drink'),
  (106, 'verbs', 'correr', 'to run'),
  (107, 'verbs', 'voar', 'to fly'),
  (108, 'verbs', 'nadar', 'to swim'),
  (109, 'verbs', 'dirigir', 'to drive'),
  (110, 'verbs', 'caminhar', 'to walk'),
  (111, 'verbs', 'viajar', 'to travel'),
  (112, 'verbs', 'visitar', 'to visit'),
  (113, 'verbs', 'curtir, desfrutar', 'to enjoy'),
  (114, 'verbs', 'estudar', 'to study'),
  (115, 'verbs', 'ensinar', 'to teach'),
  (116, 'verbs', 'aprender', 'to learn'),
  (117, 'verbs', 'ler', 'to read'),
  (118, 'verbs', 'escrever', 'to write'),
  (119, 'verbs', 'desenhar', 'to draw'),
  (120, 'verbs', 'pintar', 'to paint'),
  (121, 'verbs', 'cantar', 'to sing'),
  (122, 'verbs', 'dançar', 'to dance'),
  (123, 'verbs', 'cozinhar', 'to cook'),
  (124, 'verbs', 'lavar', 'to wash');